# Site settings
title: Kogyblack random stuff
email: kogyblack@hotmail.com
description: # this means to ignore newlines until "baseurl:"
  Website for posting random stuff like programming, game dev..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://naumazeredo.github.io" # the base hostname & protocol for your site
twitter_username: kogyblack
github_username: kogyblack

# Build settings
markdown: kramdown
